import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AppWindow,
  AudioLines,
  Bot,
  BrainCircuit,
  CalendarDays,
  Clapperboard,
  Cpu,
  CreditCard,
  Database,
  FileSearch,
  Fingerprint,
  Gauge,
  HardDrive,
  Hexagon,
  Library,
  LineChart,
  Link2,
  LockKeyhole,
  Megaphone,
  MousePointerClick,
  PanelsTopLeft,
  ScanSearch,
  ShieldCheck,
  Smartphone,
  Store,
  TabletSmartphone,
  Users,
  Waypoints,
  Workflow,
  Zap,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Activity,
  AppWindow,
  AudioLines,
  Bot,
  BrainCircuit,
  CalendarDays,
  Clapperboard,
  Cpu,
  CreditCard,
  Database,
  FileSearch,
  Fingerprint,
  Gauge,
  HardDrive,
  Hexagon,
  Library,
  LineChart,
  Link2,
  LockKeyhole,
  Megaphone,
  MousePointerClick,
  PanelsTopLeft,
  ScanSearch,
  ShieldCheck,
  Smartphone,
  Store,
  TabletSmartphone,
  Users,
  Waypoints,
  Workflow,
  Zap,
};

export function getServiceIcon(name: string): LucideIcon {
  return iconMap[name] ?? Hexagon;
}
